export const productData = [
  {
    id: 1,
    product: "S6000E",
    updated: "1 day ago",
    type: "Making Machine",
    status: "Active",
  },
  {
    id: 2,
    product: "S4000",
    updated: "1 week ago",
    type: "Making Machine",
    status: "Active",
  },
  {
    id: 3,
    product: "HLP 225",
    updated: "1 month ago",
    type: "Packing Machine",
    status: "On Hold",
  },
  {
    id: 4,
    product: "Stamper M-Type",
    updated: "30 day ago",
    type: "Packing Machine",
    status: "Active",
  },
  {
    id: 5,
    product: "S6000E",
    updated: "1 day ago",
    type: "Making Machine",
    status: "Active",
  },
  {
    id: 6,
    product: "HLP 225",
    updated: "1 month ago",
    type: "Packing Machine",
    status: "On Hold",
  },
  {
    id: 7,
    product: "S4000",
    updated: "1 week ago",
    type: "Making Machine",
    status: "Active",
  },
  {
    id: 8,
    product: "HLP 225",
    updated: "1 month ago",
    type: "Packing Machine",
    status: "On Hold",
  },
  {
    id: 9,
    product: "S4000",
    updated: "1 week ago",
    type: "Making Machine",
    status: "Active",
  },
  {
    id: 10,
    product: "Stamper M-Type",
    updated: "30 day ago",
    type: "Packing Machine",
    status: "Active",
  },
  {
    id: 11,
    product: "HLP 225",
    updated: "1 month ago",
    type: "Packing Machine",
    status: "On Hold",
  },
  {
    id: 12,
    product: "S4000",
    updated: "1 week ago",
    type: "Making Machine",
    status: "Active",
  },
  {
    id: 13,
    product: "Stamper M-Type",
    updated: "30 day ago",
    type: "Packing Machine",
    status: "Active",
  },
  {
    id: 14,
    product: "S6000E",
    updated: "1 day ago",
    type: "Making Machine",
    status: "Active",
  },
  {
    id: 15,
    product: "S4000",
    updated: "1 week ago",
    type: "Making Machine",
    status: "Active",
  },
  {
    id: 16,
    product: "HLP 225",
    updated: "1 month ago",
    type: "Packing Machine",
    status: "On Hold",
  },
  {
    id: 17,
    product: "Stamper M-Type",
    updated: "30 day ago",
    type: "Packing Machine",
    status: "Active",
  },
];
