export const applicantData = [
  {
    id: 1,
    applicant: "Syahdan",
    status: "Accepted",
    position: "Warehouse Staff",
    type: "Internship",
  },
  {
    id: 2,
    applicant: "Habi",
    status: "Waiting List",
    position: "Electrical Engineer",
    type: "Employee",
  },
  {
    id: 3,
    applicant: "Syahdan",
    status: "Waiting List",
    position: "Warehouse Staff",
    type: "Internship",
  },
  {
    id: 4,
    applicant: "Syahdan",
    status: "Waiting List",
    position: "Mechanical Engineer",
    type: "Internship",
  },
  {
    id: 5,
    applicant: "Syahdan",
    status: "Waiting List",
    position: "Warehouse Staff",
    type: "Internship",
  },
  {
    id: 6,
    applicant: "Syahdan",
    status: "Declined",
    position: "Mechanical Engineer",
    type: "Internship",
  },
  {
    id: 7,
    applicant: "Habi",
    status: "Waiting List",
    position: "Electrical Engineer",
    type: "Employee",
  },
  {
    id: 8,
    applicant: "Habi",
    status: "Waiting List",
    position: "Electrical Engineer",
    type: "Employee",
  },
  {
    id: 9,
    applicant: "Nabila",
    status: "Accepted",
    position: "CAD Designer",
    type: "Employee",
  },
  {
    id: 10,
    applicant: "Habi",
    status: "Declined",
    position: "Machine Assembler",
    type: "Employee",
  },
  {
    id: 10,
    applicant: "Habi",
    status: "Accepted",
    position: "Machine Assembler",
    type: "Internship",
  },
];
